baseURL: 'https://dslachut.github.io/'
languageCode: 'en-us'
title: 'D.S. Lachut'
theme: 'hugo-blog-awesome'
defaultContentLanguage: 'en-us'
enableEmoji: true
ignoreErrors: 'additional-script-loading-error'
